spring.application.name=rastrix
spring.datasource.url=jdbc:mysql://localhost:3306/rastrix
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

security.jwt.secret=ubxiSWZ6Fn73bF2oWJ6T835dSNW4pTYqCmV/5hPMHrw=
security.jwt.expiration-ms=86400000
